---
title: "Pilot - Amphibia"
author: "Ricardo Rodrigues da Silveira Filho"
date: "Aug 2022"
format: html
editor: source
editor_options: 
  chunk_output_type: console
---

---

#### E-mail: ricardodasilveira@gmail.com

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
Sys.setlocale(category = "LC_ALL", locale = "pt_BR.UTF-8")
```


### 0) Setup


- Dealing with species list (see script above)
- Loading *magrittr*, *panppbio* and *tidyverse* packages


```{r}
#| eval: false
source("R/speciesList.R")
```

```{r}
#| eval: false
library(magrittr)
# library(panppbio)
library(tidyverse)
```



### 1) Species list

- Amphibia - 1188 species (+ 12 old names)

```{r}
#| eval: false

# Dataframe with brazilian amphibian species
amp_splist <- readr::read_csv(here::here("data/processed/amp_splist.csv"),
							  show_col_types = FALSE) 

# Dataframe with the old amphibian names (12)
source(here::here("R/insert_amp.R"))

# Inserting 12 old valid names (see `insert_amp`)
amp_splist %<>% 
	rows_insert(., insert_amp, by = "id_list")
	
# First six observations of the dataframe
amp_splist %>% 
	head()

# Number of species
amp_splist %>% 
	tally()

```



### 2) BOLD Systems


#### 2.1) Searching using class and country

```{r}
#| eval: false

# Searching on BOLD Systems
search_amp_br <- bold::bold_specimens(taxon = "Amphibia",
									  geo = "Brazil")

# Writing the data in a file
readr::write_csv(search_amp_br, here::here("data/processed/search_amp_br.csv"))

```


```{r}
#| eval: false

# Reading data above
search_amp_br <- readr::read_csv(here::here("data/processed/search_amp_br.csv"),
								show_col_types = FALSE)

# Checking the data
search_amp_br %>% 
	glimpse


# Total number of observations
search_amp_br %>% 
	tally()

```



#### 2.2) Searching by species name


```{r}
#| eval: false

# Searching on BOLD Systems using the whole species name

source(here::here("R/bold_onebyone.R"))

search_amp_spp <- bold_onebyone(data = amp_splist, 
								speciesvar = "species")




```


#### 2.3) Names correction and updates

```{r}
#| eval: false


```



